config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search' => 'pages#search'
  get '/access_token' => 'pages#access_token'
  get '/mydata' => 'pages#my_data'
  get '/subreddit' => 'pages#lsit_subreddit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #Con esto se transforma el código a hash de json
  require 'oj'
  
  #Muestra en la página
  def index
  end
  
  #Manda a llamar a la función que da el acces token
  def access_token
    #El @ es como un this.algo
    #Aquí se guardan todos los datos que mandó de respuesta cuando se pidió el token
    @response = request_access_token
    #Se guarda el puro token
    @access_token = @response["access_token"]
    #Se pone un mensaje en pantalla con el token en el index.html.erb se explica
    @message = "Your Access Token is #{@response}"
    #actualiza la página pero actualizada con la información
    render action: :index
  end

  #Manda a llamar la función que recibe el subreddit ingresado que se va a buscar para regresar la información guardada
  def search
    #se guarda la lista que se encontró en el subreddit
    @subreddit = list_subreddit(params[:subreddit])
    #Si no encuentra el subreddit pone el mensaje
    unless @subreddit
      @message = 'No Links found or Incorrect Subreddit'
    end
    render action: :index
  end

  #Manda a llamar a la función que regresa la info de un usuario
  def my_data
    #guarda la información de usuario
    response = get_my_data
    #Se guarda el puro nombre
    @name = response["name"]
    #Se guarda la imágen
    @image = response["icon_img"]
    #se guarda la url
    @url = response["subreddit"]["url"]
    #se guarda el tipo de usuario
    @user_type = response["subreddit"]["subreddit_type"]
    #igual actualiza
    render action: :index
  end
  
  #Manda a llamar a la función que busca el top 10 de un subreddit
  def list_subreddit(subreddit)
    #se guarda el token
    access_token = request_access_token["access_token"]
    #se guarda la info del subreddit
    @about = about(subreddit, access_token)
    #Guarda la info de los posts
    response = retrieve_posts(subreddit, access_token)
    #Guarda la info de los hijos del post tal cual
    @submissions = response["data"]["children"]
  end

  #De aquí en adelante se vuelven privadas las funciónes porque #BuenCódigo
  private

  #Pide el access token
  def request_access_token
    #Se trae y guarda la info del usuario desde el local_env.yml
    client_id = ENV["CLIENT_ID"]
    client_secret = ENV["CLIENT_SECRET_ID"]
    username = ENV["USERNAME"]
    password = ENV["PASSWORD"]
    #url para pedir el token
    url = 'https://www.reddit.com/api/v1/access_token'
    #Se codifica porque #Reddit el cliente y el secret id
    combo = "#{client_id}:#{client_secret}"
    combo_encoded = Base64.encode64(combo).strip
    headers = "Basic #{combo_encoded}" 
    #se pone el body de la url
    body = "grant_type=password&username=#{username}&password=#{password}"
    #Faraday es para hacer la conexión con el html del token 
    conn = Faraday.new(url)
    #Ya estando en la conexión se manda el resto de atributos que necesita para tener el acces token
    response = conn.post do |req|
      #no se modifica la url
      req.url ''
      #Se mandan las credenciales en Authoritzation
      req.headers['Authorization'] = headers
      #Se actualiza el body
      req.body = body
    end
    #Convierte la respuesta en hashes de json
    body = Oj.load(response.body)
  end

  #Recibe los datos de usuario
  def get_my_data
    access_token = request_access_token["access_token"]
    #Ahora se usará este tipo de url para acceder a la información con el acces token
    url = "https://oauth.reddit.com/api/v1/me"
    #Se guarda el acces token
    headers = "Bearer #{access_token}" 
    conn = Faraday.new(
      url
    )
    response = conn.get do |req|
      req.url ''
      req.headers['Authorization'] = headers
    end
    body = Oj.load(response.body)
  end

  #Pide la info de un subreddit
  def about(subreddit,access_token)
    #Solo cambia la url nada más
    url = "https://oauth.reddit.com/r/#{subreddit}/about"
    headers = "Bearer #{access_token}" 
    conn = Faraday.new(url)
    response = conn.get do |req|
      req.url ''
      req.headers['Authorization'] = headers
    end

    body = Oj.load(response.body)
  end

  #Recibe el los post top 10 de un subreddit
  def retrieve_posts(subreddit, access_token)
    url = "https://oauth.reddit.com/r/#{subreddit}/top/.json?limit=10"
    headers = "Bearer #{access_token}"
    conn = Faraday.new(url)
    response = conn.get do |req|
      req.url ''
      req.headers['Authorization'] = headers
    end
    body = Oj.load(response.body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProjectSkeleton</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<!-- app/views/travel/index.html.erb -->
<div class="container">
  <div class="row">
    <div class="col-lg-12 mt-5">
       
      <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: access_token_path, method: 'get', local: true) do %>
          <%= button_tag 'Get Access Token', class: 'btn btn-success btn-block' %>
        <% end %>
      </div>

       <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: mydata_path, method: 'get', local: true) do %>
          <%= button_tag 'My Data', class: 'btn btn-success btn-block' %>
        <% end %>
      </div>

      <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: search_path, method: 'get', local: true) do %>
          <div class="form-group">
            <%= label_tag :subreddit, 'Search for a subreddit links '%>
            <%= text_field_tag :subreddit, nil, placeholder: 'r/', class: 'form-control' %>
          </div>
          <%= button_tag 'Search Subreddit', class: 'btn btn-success btn-block' %>
        <% end %>
      </div>
    </div>

     <% if @message %>
          <div class="alert alert-warning"><%= @message %></div>
        <% end %>

    <% if @profile %>  
        <div>
          <p> My Name: <%= @name %></p>
          <br>
          <a href="http://www.reddit.com<%=@url%>"><%= @url %></a>
          <br>
          <img src="<%=@image%>">
          <br>
          <p>User Status: <%= @user_type %></p>
        </div>
    <% end %>

    <% if @about %>  
        <div>
          <p>Subreddit: <%= @about["data"]["display_name"] %></p>
          <p>Title: <%= @about["data"]["title"] %></p>
          <p>Accounts Active: <%= @about["data"]["accounts_active"] %></p>
          <p>Category: <%= @about["data"]["advertiser_category"] %></p>
          <a href="http://www.reddit.com<%=@about["data"]["url"]%>"><%= @about["data"]["url"] %></a>
        </div>
    <% end %>

    <% if @submissions %>  
      <% @submissions.each do |entry| %>
        <div>
          <p>Title: <%= entry["data"]["title"] %></p>
          <p>UpVote Ratio: <%= entry["data"]["upvote_ratio"] %></p>
          <p>Author: <%= entry["data"]["author"] %></p>
        </div>
        <br><br>
      <% end %>
    <% end %>


  </div>
</div>